### PR TITLE
ignore(ci): bump deps

### LINKED ISSUE #447: update dependencies on CI
goodtables is now frictionless
bump travis to more recent VM
update python version
update basex (if i can find out how on CI)

problem https://github.com/frictionlessdata/frictionless-py/issues/614

### PR DESCRIPTION
**Pull request by duncdrum**
bump dependencies to more recent version ~~where this is straightforward~~ on CI

close #447

### CODE REVIEW

**Comment by duncdrum** [comment]
ok i found and fixed the wrong resource descriptors, but now i m struggling with lading schemas from `path` expressions, @whalekeykeeper feel free have a go at it just create a new branch of this one.

**Comment by whalekeykeeper** [comment]
> ok i found and fixed the wrong resource descriptors, but now i m struggling with lading schemas from `path` expressions, @whalekeykeeper feel free have a go at it just create a new branch of this one.

First I would like to ask what do you mean by saying "land schemas from path expression". Can you explain a bit which part of CI it is in?
Secondly, sorry I happen to click on "ready to review" button. I want to undo it by following this page :https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request. But I cannot see the "convert to draft" button.

**Comment by duncdrum** [comment]
If you look at the log on Travis you ll see 

‘‘‘shell
resource-error  The data resource has an error: "'schema/Act.json' is not of type 'object'" at "schema" in metadata and at "properties/schema/type" in profile
‘‘‘

Ie the Schema isn't loaded from the ‘path‘ expression to the external schema file. It is loaded when copying the contents into the ‘darapackage.json‘ this should be fixed with the next update of frictionless

**Comment by duncdrum** [comment]
ping @whalekeykeeper

**Pull request merged**
