### PR TITLE
SF 3

### PR DESCRIPTION
**Pull request by mira-gruenwald**
readings in SF - works. Please have a look :)

### Checklist
-   The title line explains what these changes do
-   All my changes are marked in the `last_modfied` column
-   The PR has no merge conflicts
-   Travis checks are passing

### CODE REVIEW

**Comment by duncdrum** [comment]
@whalekeykeeper since we've lost travis for this branch we'll need to run the test manually. Could you do us the honors and report the results in here. thx

P.S.: Yes this is a didactic assignment ;-)

**Comment by whalekeykeeper** [comment]
Am I understanding this correctly? I should manually execute what are defined previously in the `.travis.yml `, i.e., to: 
`Generate xml files`; 
`expand xincludes`; 
then `check` by imitate the following operations: 
```script:
  - frictionless validate csv/datapackage.json
  # - bats --tap test/*.bats
  - jing xml/schema/tei_all.rng xml/expand/expand.xml
  - jing xml/schema/gexf.rng xml/rActs.gexf
  ```

**Comment by duncdrum** [comment]
Yes but just the tests which are defined in the Travis file from this branch.

**Comment by whalekeykeeper** [comment]
The results of testing with `csvlint` are (ignored valid ones):
```
data/Act.csv is INVALID
1. act_id: unique. Row: 1380,1. A01843
1. start: inconsistent_values. Column: 6
2. end: inconsistent_values. Column: 7
3. page: inconsistent_values. Column: 11

data/Person.csv is INVALID
1. birthyear: pattern. Row: 1557,10. 778
2. deathyear: pattern. Row: 1557,11. 897
3. birthyear: pattern. Row: 1558,10. 778
4. deathyear: pattern. Row: 1558,11. 897
5. family_name: missing_value. Row: 1577,2. 
6. family_name: missing_value. Row: 1605,2. 
7. sex: pattern. Row: 1620,5. 
8. sex: missing_value. Row: 1620,5. 
9. source_1: pattern. Row: 1620,18. 
10. source_1: missing_value. Row: 1620,18. 
11. sex: pattern. Row: 1621,5. 
12. sex: missing_value. Row: 1621,5. 
13. source_1: pattern. Row: 1621,18. 
14. source_1: missing_value. Row: 1621,18. 
15. sex: pattern. Row: 1622,5. 
16. sex: missing_value. Row: 1622,5. 
17. source_1: pattern. Row: 1622,18. 
18. source_1: missing_value. Row: 1622,18. 
19. source_1: pattern. Row: 1625,18. 
20. source_1: missing_value. Row: 1625,18. 
1. birthyear: inconsistent_values. Column: 10
2. source_1: inconsistent_values. Column: 18
3. source_2: inconsistent_values. Column: 20
4. page_2: inconsistent_values. Column: 21

data/PrimarySource.csv is INVALID
1. first_chin_edition: pattern. Row: 1338,10. -139
2. first_chin_edition: pattern. Row: 1339,10. -139
3. title: missing_value. Row: 1382,2. 
4. author: pattern. Row: 1385,5. 
5. author: missing_value. Row: 1385,5. 
6. genre: pattern. Row: 1385,6. 
7. genre: missing_value. Row: 1385,6. 
8. author: pattern. Row: 1386,5. 
9. author: missing_value. Row: 1386,5. 
10. genre: pattern. Row: 1386,6. 
11. genre: missing_value. Row: 1386,6. 
1. publication_date: inconsistent_values. Column: 8
2. first_chin_edition: inconsistent_values. Column: 10

data/PrimarySource.csv is INVALID
1. first_chin_edition: pattern. Row: 1338,10. -139
2. first_chin_edition: pattern. Row: 1339,10. -139
3. title: missing_value. Row: 1382,2. 
4. author: pattern. Row: 1385,5. 
5. author: missing_value. Row: 1385,5. 
6. genre: pattern. Row: 1385,6. 
7. genre: missing_value. Row: 1385,6. 
8. author: pattern. Row: 1386,5. 
9. author: missing_value. Row: 1386,5. 
10. genre: pattern. Row: 1386,6. 
11. genre: missing_value. Row: 1386,6. 
1. publication_date: inconsistent_values. Column: 8
2. first_chin_edition: inconsistent_values. Column: 10
``` 

For command `bats --tap test/*.bats`:
```
1..31
not ok 1 person foreign keys in Act.agent are resolvable
# (in test file test/Acts.bats, line 12)
#   `[ "${lines[1]}" -eq 1 ]' failed
ok 2 act type foreign keys in Act.action are resolvable
ok 3 primary source foreign keys in Act.act_object are resolvable
ok 4 works foreign keys in Act.act_object are resolvable
ok 5 person foreign keys in Act.act_object are resolvable
ok 6 genres foreign keys in Act.act_object are resolvable
ok 7 quotes foreign keys in Act.act_object are resolvable
ok 8 secondaries source foreign keys in Act.source are resolvable
ok 9 place foreign keys in Institution.place are resolvable
ok 10 group foreign keys in Membership.institution are resolvable
ok 11 person foreign keys in Membership.member are resolvable
ok 12 secondary source foreign keys in Membership.source are resolvable
ok 13 place foreign keys in Person.place_of_rust are resolvable
ok 14 place foreign keys in Person.place_of_birth are resolvable
ok 15 place foreign keys in Person.place_of_death are resolvable
ok 16 status foreign keys in Person.social_position are resolvable
ok 17 person foreign keys in SocialRelation.ego are resolvable
ok 18 person foreign keys in SocialRelation.person_id are resolvable
ok 19 person foreign keys in PrimarySource.author are resolvable
ok 20 group foreign keys in PrimarySource.author are resolvable
not ok 21 genre foreign keys in PrimarySource.genre are resolvable
# (in test file test/Texts.bats, line 18)
#   `[ "${lines[1]}" -eq 0 ]' failed
ok 22 place foreign keys in PrimarySource.publication_place are resolvable
ok 23 person foreign keys in SecondarySource.author are resolvable
ok 24 group foreign keys in SecondarySource.author are resolvable
ok 25 genre foreign keys in SecondarySource.genre are resolvable
ok 26 place foreign keys in SecondarySource.publication_place are resolvable
ok 27 primary source foreign keys in Quotation.source are resolvable
ok 28 secondary source foreign keys in Quotation.source_id are resolvable
ok 29 person foreign keys in ArtWork.creator are resolvable
ok 30 group foreign keys in ArtWork.creator are resolvables
ok 31 artform foreign keys in ArtWork.art_form are resolvable
```

**Comment by whalekeykeeper** [comment]
Update with a new round of tests with `csvlint`:
```
data/Genre.csv is INVALID
1. genre_id: unique. Row: 73,1. G88

data/Membership.csv is INVALID
1. source: pattern. Row: 25,3. 
2. source: missing_value. Row: 25,3. 
3. source: pattern. Row: 26,3. 
4. source: missing_value. Row: 26,3. 
1. page: inconsistent_values. Column: 4

data/PrimarySource.csv is INVALID
1. neibu: pattern. Row: 1334,11. PS00931
2. neibu: pattern. Row: 1335,11. PS00931
1. publication_date: inconsistent_values. Column: 8
2. first_chin_edition: inconsistent_values. Column: 10

```

One question here: Is `inconsistent` allowed while the file is `VALID`? Example: 
```
data/SocialRelation.csv is VALID
1. page: inconsistent_values. Column: 8
```

For command bats --tap test/*.bats:
```
1..31
not ok 1 person foreign keys in Act.agent are resolvable
# (in test file test/Acts.bats, line 12)
#   `[ "${lines[1]}" -eq 1 ]' failed
ok 2 act type foreign keys in Act.action are resolvable
ok 3 primary source foreign keys in Act.act_object are resolvable
ok 4 works foreign keys in Act.act_object are resolvable
ok 5 person foreign keys in Act.act_object are resolvable
ok 6 genres foreign keys in Act.act_object are resolvable
ok 7 quotes foreign keys in Act.act_object are resolvable
ok 8 secondaries source foreign keys in Act.source are resolvable
ok 9 place foreign keys in Institution.place are resolvable
ok 10 group foreign keys in Membership.institution are resolvable
ok 11 person foreign keys in Membership.member are resolvable
ok 12 secondary source foreign keys in Membership.source are resolvable
ok 13 place foreign keys in Person.place_of_rust are resolvable
ok 14 place foreign keys in Person.place_of_birth are resolvable
ok 15 place foreign keys in Person.place_of_death are resolvable
ok 16 status foreign keys in Person.social_position are resolvable
ok 17 person foreign keys in SocialRelation.ego are resolvable
ok 18 person foreign keys in SocialRelation.person_id are resolvable
ok 19 person foreign keys in PrimarySource.author are resolvable
ok 20 group foreign keys in PrimarySource.author are resolvable
ok 21 genre foreign keys in PrimarySource.genre are resolvable
ok 22 place foreign keys in PrimarySource.publication_place are resolvable
ok 23 person foreign keys in SecondarySource.author are resolvable
ok 24 group foreign keys in SecondarySource.author are resolvable
ok 25 genre foreign keys in SecondarySource.genre are resolvable
ok 26 place foreign keys in SecondarySource.publication_place are resolvable
ok 27 primary source foreign keys in Quotation.source are resolvable
ok 28 secondary source foreign keys in Quotation.source_id are resolvable
ok 29 person foreign keys in ArtWork.creator are resolvable
ok 30 group foreign keys in ArtWork.creator are resolvables
ok 31 artform foreign keys in ArtWork.art_form are resolvable
```

**Comment by duncdrum** [comment]
@mira-gruenwald and @whalekeykeeper great work, thank you both. 

The `inconsistent` on a `VALID` file are warnings informing you about apparent inconsistencies, without breaking any rules. 

we need to address the outstanding csvlint errors, i ll take a look at the bats error myself later, i think this might be a false positive, but i ll have to check.

**Comment by mira-gruenwald** [comment]
Hi @duncdrum hi @whalekeykeeper  
Some data was deleted by this commit-revert ...actually all corrections and recent commits.  
Can I still change the files now or should we fix this first?

**Comment by duncdrum** [comment]
@mira-gruenwald just wait a little longer please i ll fix this within the next 2-3 hours.

**Comment by whalekeykeeper** [comment]
Update:
```
data/Genre.csv is INVALID
1. genre_id: unique. Row: 73,1. G88

data/Membership.csv is INVALID
1. source: pattern. Row: 25,3. 
2. source: missing_value. Row: 25,3. 
3. source: pattern. Row: 26,3. 
4. source: missing_value. Row: 26,3. 
1. page: inconsistent_values. Column: 4

data/PrimarySource.csv is INVALID
1. neibu: pattern. Row: 1334,11. PS00931
2. neibu: pattern. Row: 1335,11. PS00931
1. publication_date: inconsistent_values. Column: 8
2. first_chin_edition: inconsistent_values. Column: 10
```

For `bats`:
```
1..31
not ok 1 person foreign keys in Act.agent are resolvable
# (in test file test/Acts.bats, line 12)
#   `[ "${lines[1]}" -eq 1 ]' failed
ok 2 act type foreign keys in Act.action are resolvable
ok 3 primary source foreign keys in Act.act_object are resolvable
ok 4 works foreign keys in Act.act_object are resolvable
ok 5 person foreign keys in Act.act_object are resolvable
ok 6 genres foreign keys in Act.act_object are resolvable
ok 7 quotes foreign keys in Act.act_object are resolvable
ok 8 secondaries source foreign keys in Act.source are resolvable
ok 9 place foreign keys in Institution.place are resolvable
ok 10 group foreign keys in Membership.institution are resolvable
ok 11 person foreign keys in Membership.member are resolvable
ok 12 secondary source foreign keys in Membership.source are resolvable
ok 13 place foreign keys in Person.place_of_rust are resolvable
ok 14 place foreign keys in Person.place_of_birth are resolvable
ok 15 place foreign keys in Person.place_of_death are resolvable
ok 16 status foreign keys in Person.social_position are resolvable
ok 17 person foreign keys in SocialRelation.ego are resolvable
ok 18 person foreign keys in SocialRelation.person_id are resolvable
ok 19 person foreign keys in PrimarySource.author are resolvable
ok 20 group foreign keys in PrimarySource.author are resolvable
ok 21 genre foreign keys in PrimarySource.genre are resolvable
ok 22 place foreign keys in PrimarySource.publication_place are resolvable
ok 23 person foreign keys in SecondarySource.author are resolvable
ok 24 group foreign keys in SecondarySource.author are resolvable
ok 25 genre foreign keys in SecondarySource.genre are resolvable
ok 26 place foreign keys in SecondarySource.publication_place are resolvable
ok 27 primary source foreign keys in Quotation.source are resolvable
ok 28 secondary source foreign keys in Quotation.source_id are resolvable
ok 29 person foreign keys in ArtWork.creator are resolvable
ok 30 group foreign keys in ArtWork.creator are resolvables
ok 31 artform foreign keys in ArtWork.art_form are resolvable
```

**Comment by whalekeykeeper** [comment]
Updates:
```
data/PrimarySource.csv is INVALID
1. first_chin_edition: pattern. Row: 1338,10. -139
2. first_chin_edition: pattern. Row: 1339,10. -139
1. publication_date: inconsistent_values. Column: 8
2. first_chin_edition: inconsistent_values. Column: 10
```

**Comment by whalekeykeeper** [comment]
Passed all tests with `csvlint`:
All CSV files are VALID! Yeah! @mira-gruenwald 

For `bats`:
```
1..31
not ok 1 person foreign keys in Act.agent are resolvable
# (in test file test/Acts.bats, line 12)
#   `[ "${lines[1]}" -eq 1 ]' failed
```

**Comment by duncdrum** [comment]
well done @mira-gruenwald and @whalekeykeeper I ll take over from here. 

I ll try to merge this into the `2.0-literature` branch, and then start getting that into shape for the next release.

**Pull request merged**
