### PR TITLE
add linked csv files

### PR DESCRIPTION
**Pull request by duncdrum**
Add `Act`, `PrimarySource`, `SecondarySource`, & `Genre` csv files as external data to new spreadsheet. 
These are linked to the `2.0-fiction` branch. 

I also added some notes on how to do this to the wiki.

- Open table here on Github in the browser (check branch!) then click `raw`
Screenshot 2021-07-30 at 14 41 27
- Copy the RAW URL
Screenshot 2021-07-30 at 14 41 45
- In LibreOffice select `sheet > external data`
Screenshot 2021-07-30 at 14 40 48
- paste URL and hit `ENTER`
Screenshot 2021-07-30 at 14 42 00
- make sure to select `text` as column type (same as when editing), then confirm
Screenshot 2021-07-30 at 14 42 17

### CODE REVIEW

**Review by LenaHenningsen — APPROVED** [review]

**Comment by LenaHenningsen** [comment]
Hi Duncan, what I am uncertain now is: can I still use my earlier spreadsheet or do I have to do it again? And: do I need to be online when working on the spreadsheets later. (Will be doing this on the train on Monday, I guess...).
Thanks much, Lena

**Comment by duncdrum** [comment]
You won’t need to be online, but obviously no updates from the server happen while offline. If you put filters on e.g. Act.csv. I would apply these again on linked_Act and then delete the old sheet.

**Comment by LenaHenningsen** [comment]
Hi Duncan, thanks for the explanations. I arrived at LibreOffice, but I cannot for some reason chose the "text" option. The field is there, but I cannot make a choice; otherwise my screen looks the same as yours... any idea?

**Comment by duncdrum** [comment]
You need to select the columns in the little table preview, clicking in the upper left corner of that mini-table will select all columns. However, the tables csv tables are already imported, you might see an confirmation dialogue about updating. But that should be all that is necessary. Unless you want to import and link more tables.

**Comment by LenaHenningsen** [comment]
I think my mistake was to open a new, empty sheet. I now use the one from GitHub (SF first attempts), is that correct?

**Pull request merged**
