### PR TITLE
Readings in the king of children

### PR DESCRIPTION
**Pull request by mira-gruenwald**
> Readings in _The King of Children_by A Cheng

### Please indicate issues related to this PR (if any)
See #427  .

### Checklist
-   The title line explains what these changes do
-   All my changes are marked in the `last_modfied` column
-   The PR has no merge conflicts
-   Travis checks are passing

### CODE REVIEW

**Comment by mira-gruenwald** [comment]
Checks failed because I added AWxxxx as source in Person.csv. It's the protagonist in Red Lantern, so the source is Artwork not PrimarySource. Should I change the schema then?

**Comment by duncdrum** [comment]
@mira-gruenwald not necessary, as the refactoring i did for `1.0` already takes care of that. All schemas have been updated already and put into this repo, i ll take a look when i refactor the 2.0 branch in a little while

**Comment by duncdrum** [comment]
@mira-gruenwald sorry i lost track of this, are these acts part of the the last PR or do they still need to get merged separately.

**Comment by mira-gruenwald** [comment]
Hi @duncdrum , they still need to get merged

**Comment by duncdrum** [comment]
To keep track the only error: 
```
data/Person.csv is INVALID
1. source_1: pattern. Row: 1432,18. AW00084
2. source_1: pattern. Row: 1433,18. AW00084
1. birthyear: inconsistent_values. Column: 10
2. source_1: inconsistent_values. Column: 18
3. source_2: inconsistent_values. Column: 20
4. page_2: inconsistent_values. Column: 21
```

**Comment by duncdrum** [comment]
Superseded by #474

**Pull request closed without merging**
